name: LKYRunner Push Test

on:
  push:
    branches:
      - main   
      - features/**

jobs:
  test-job:
   
    runs-on:self-hosted

    steps:
      - name: Say Hello (Bypass Execution Policy)
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -Command "Write-Output '✅ Hello! LKYRunner is working correctly on Windows X64 🎉'"
