name: LKYRunner Push Test

on:
  push:
    branches:
      - main   
      - features/**

jobs:
  test-job:
   
    runs-on:self-hosted

    steps:
      - name: Say Hello (Bypass Execution Policy)
        run: echo " Dhondu Maharaj "
          
