name: LKYRunner Push Test

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: LKYRunner   # 👈 colon ke baad space hona chahiye

    steps:
      - name: Say Hello
        shell: powershell
        run: |
          powershell -ExecutionPolicy Bypass -Command "Write-Output '✅ Hello! LKYRunner is working correctly on Windows X64 🎉'"
