name: LKYRunner Test

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Say Hello
        run: echo "✅ Hello! LKYRunner is working correctly on Windows X64 🎉"
