name: Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Print Hello
        run: echo Hello from self-hosted runner!

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: dir
